POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Testing a blog post with the second user as creator",
    "author": "Michael Write",
    "url": "www.blogs.com/3/",
    "likes": 9
}